# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gewusel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2)),
                ('nicename', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gewusel.Country'),
            preserve_default=False,
        ),
    ]
