# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gewusel', '0002_auto_20160705_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gewusel.Game')),
                ('patrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gewusel.Patrol')),
            ],
        ),
    ]
