# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 06:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gewusel', '0004_points_datetime_entered'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='entered_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
