# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gewusel', '0005_points_entered_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='patrol',
            name='subcamp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gewusel.Subcamp'),
            preserve_default=False,
        ),
    ]
