# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gewusel', '0007_auto_20160724_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcamp',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='patrol',
            unique_together=set([('name', 'group')]),
        ),
    ]
