# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gewusel', '0009_auto_20160724_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting', models.CharField(max_length=80, unique=True)),
                ('value', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['country__nicename', 'name']},
        ),
        migrations.AlterModelOptions(
            name='patrol',
            options={'ordering': ['subcamp__name', 'group__country__nicename', 'group__name']},
        ),
        migrations.AlterModelOptions(
            name='points',
            options={'ordering': ['-datetime_entered']},
        ),
        migrations.AlterModelOptions(
            name='subcamp',
            options={'ordering': ['name']},
        ),
    ]
