# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gewusel', '0010_auto_20160804_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='points',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
